name: Linux CI

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Configure (release + max optimizations)
        run: cmake --preset linux-gcc-release -D CMAKE_C_FLAGS_RELEASE="-O3 -DNDEBUG -march=native"

      - name: Build
        run: cmake --build --preset linux-gcc-release

      - name: Test
        run: ctest --preset linux-gcc-release

      - name: Smoke test CLI (list benchmarks)
        run: ./build/linux-gcc-release/hwbench-c --list
